const CHECK_FOR_UPDATE_PENDING = "CHECK_FOR_UPDATE_PENDING";
const CHECK_FOR_UPDATE_SUCCESS = "CHECK_FOR_UPDATE_SUCCESS";
const CHECK_FOR_UPDATE_FAILURE = "CHECK_FOR_UPDATE_FAILURE";

const DOWNLOAD_UPDATE_PENDING = "DOWNLOAD_UPDATE_PENDING";
const DOWNLOAD_UPDATE_SUCCESS = "DOWNLOAD_UPDATE_SUCCESS";
const DOWNLOAD_UPDATE_FAILURE = "DOWNLOAD_UPDATE_FAILURE";

const QUIT_AND_INSTALL_UPDATE = "QUIT_AND_INSTALL_UPDATE";

const APP_VERSION = "APP_VERSION";

const ELECTRON_STORE_GET = "ELECTRON_STORE_GET";
const ELECTRON_STORE_SET = "ELECTRON_STORE_SET";

export {
	CHECK_FOR_UPDATE_PENDING,
	CHECK_FOR_UPDATE_SUCCESS,
	CHECK_FOR_UPDATE_FAILURE,
	DOWNLOAD_UPDATE_PENDING,
	DOWNLOAD_UPDATE_SUCCESS,
	DOWNLOAD_UPDATE_FAILURE,
	QUIT_AND_INSTALL_UPDATE,
	APP_VERSION,
	ELECTRON_STORE_GET,
	ELECTRON_STORE_SET,
};
