import _ from 'lodash';
import React from 'react';
import {
	DateRange,
	MultipleSelect,
	Row,
	SliderRange
	} from './Row';
import { lang } from '../../../../translation/i18n';
import { translationPath } from '../../../../utils/getPath';
import { TreeType } from 'src/types/_types';
import { useTranslation } from 'react-i18next';
interface IActive {
	values: any;
	active: boolean;
	activeFilterContent: any;
}
export const Active = ({ active, values, activeFilterContent }: IActive) => {
	const { t } = useTranslation();
	return (
		<>
			<>
				{_.isEqual(activeFilterContent, values)
					? t(translationPath(lang.filter.activeFilters).path)
					: t(translationPath(lang.filter.selectedFilters).path)}
			</>
			<Row
				title={t(translationPath(lang.common.forename).path)}
				value={values?.Customers?.FirstNameFilter?.FirstName}
				show={!!values?.Customers?.FirstNameFilter.FirstName}
				type={TreeType.CUSTOMER}
			/>
			<Row
				title={t(translationPath(lang.common.surname).path)}
				value={values?.Customers?.LastNameFilter?.LastName}
				show={!!values?.Customers?.LastNameFilter?.LastName}
				type={TreeType.CUSTOMER}
			/>
			<Row
				title={t(translationPath(lang.common.companyName).path)}
				value={values?.Customers?.CompanyNameFilter?.Name}
				show={!!values?.Customers?.CompanyNameFilter?.Name}
				type={TreeType.CUSTOMER}
			/>
			<Row
				title={t(translationPath(lang.common.crn).path)}
				value={values?.Customers?.CrnFilter?.Crn}
				show={!!values?.Customers?.CrnFilter?.Crn}
				type={TreeType.CUSTOMER}
			/>
			<Row
				title={t(translationPath(lang.common.vatRegNo).path)}
				value={values?.Customers?.VatNumberFilter?.VatNumber}
				show={!!values?.Customers?.VatNumberFilter?.VatNumber}
				type={TreeType.CUSTOMER}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.type).path)}
				value={values?.Customers?.CustomerTypeFilter?.Customers}
				show={values?.Customers?.CustomerTypeFilter?.Active}
				translate
				type={TreeType.CUSTOMER}
			/>
			<SliderRange
				title={t(
					translationPath(lang.common.averagePricePerProjectFilter).path
				)}
				value={values?.Customers?.AveragePricePerProjectFilter}
				show={values?.Customers?.AveragePricePerProjectFilter?.Active}
				type={TreeType.CUSTOMER}
			/>
			<SliderRange
				title={t(translationPath(lang.common.sumOfProjectPricesFilter).path)}
				value={values?.Customers?.SumOfProjectPricesFilter}
				show={values?.Customers?.SumOfProjectPricesFilter?.Active}
				type={TreeType.CUSTOMER}
			/>
			<SliderRange
				title={t(translationPath(lang.common.numberOfProjectsFilter).path)}
				value={values?.Customers?.NumberOfProjectsFilter}
				show={values?.Customers?.NumberOfProjectsFilter?.Active}
				round
				type={TreeType.CUSTOMER}
			/>
			<SliderRange
				title={t(translationPath(lang.common.finishedQuotationCount).path)}
				value={values?.Customers?.NumberOfQuotationsFilter}
				show={values?.Customers?.NumberOfQuotationsFilter?.Active}
				round
				type={TreeType.CUSTOMER}
			/>
			<SliderRange
				title={t(translationPath(lang.common.finishedProductionCount).path)}
				value={values?.Customers?.NumberOfProductionsFilter}
				show={values?.Customers?.NumberOfProductionsFilter?.Active}
				round
				type={TreeType.CUSTOMER}
			/>
			<SliderRange
				title={t(
					translationPath(lang.common.productionsPerQuotationsFilter).path
				)}
				value={values?.Customers?.ProductionsPerQuotationsFilter}
				show={values?.Customers?.ProductionsPerQuotationsFilter?.Active}
				type={TreeType.CUSTOMER}
			/>
			<DateRange
				title={t(
					translationPath(lang.common.customerDateOfCreationFilter).path
				)}
				value={values?.Customers?.CustomerDateOfCreationFilter}
				show={values?.Customers?.CustomerDateOfCreationFilter?.Active}
				type={TreeType.CUSTOMER}
			/>
			<Row
				title={t(translationPath(lang.common.projectName).path)}
				value={values?.Projects?.NameFilter?.Name}
				show={!!values?.Projects?.NameFilter?.Name}
				type={TreeType.PROJECT}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.user).path)}
				value={values?.Projects?.UserFilter?.Name}
				show={values?.Projects?.UserFilter?.Active}
				includeNotSetTooltip={t(
					translationPath(lang.common.tooltip.projectUserFilter).path
				)}
				includeNotSet={values?.UserFilter?.IncludeNotSet}
				translate
				string
				type={TreeType.PROJECT}
			/>
			<Row
				title={t(translationPath(lang.common.address).path)}
				value={values?.Projects?.AddressFilter?.Location}
				show={!!values?.Projects?.AddressFilter?.Location}
				includeNotSet={values?.AddressFilter?.IncludeNotSet}
				includeNotSetTooltip={t(
					translationPath(lang.common.tooltip.addressFilter).path
				)}
				type={TreeType.PROJECT}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.projectState).path)}
				value={values?.Projects?.ProjectStateFilter?.ProjectStates}
				show={values?.Projects?.ProjectStateFilter?.Active}
				translate
				type={TreeType.PROJECT}
			/>
			<DateRange
				title={t(translationPath(lang.common.projectTimeOfCreation).path)}
				value={values?.Projects?.DateOfCreationFilter}
				show={values?.Projects?.DateOfCreationFilter?.Active}
				type={TreeType.PROJECT}
			/>
			<DateRange
				title={t(translationPath(lang.common.quotationDate).path)}
				value={values?.Projects?.QuotationDateFilter}
				show={values?.Projects?.QuotationDateFilter?.Active}
				type={TreeType.PROJECT}
			/>
			<DateRange
				title={t(translationPath(lang.common.constructionDate).path)}
				value={values?.Projects?.ConstructionDateFilter}
				show={values?.Projects?.ConstructionDateFilter?.Active}
				type={TreeType.PROJECT}
			/>
			<SliderRange
				title={t(translationPath(lang.common.quotation).path)}
				value={values?.Projects?.QuotationPriceFilter}
				show={values?.Projects?.QuotationPriceFilter?.Active}
				type={TreeType.PROJECT}
			/>
			<SliderRange
				title={t(translationPath(lang.common.production).path)}
				value={values?.Projects?.ProductionPriceFilter}
				show={values?.Projects?.ProductionPriceFilter?.Active}
				type={TreeType.PROJECT}
			/>
			<Row
				title={t(translationPath(lang.common.jobName).path)}
				value={values?.Jobs?.NameFilter?.Name}
				show={!!values?.Jobs?.NameFilter?.Name}
				type={TreeType.JOB}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.jobType).path)}
				value={values?.Jobs?.JobTypeFilter?.JobTypes}
				show={values?.Jobs?.JobTypeFilter?.Active}
				translate
				type={TreeType.JOB}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.jobState).path)}
				value={values?.Jobs?.JobStateFilter?.JobStates}
				show={values?.Jobs?.JobStateFilter?.Active}
				translate
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.designPrice).path)}
				value={values?.Jobs?.PriceFilter}
				show={values?.Jobs?.PriceFilter?.Active}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.pricePerSquareMeter).path)}
				value={values?.Jobs?.PricePerSquareMeterFilter}
				show={values?.Jobs?.PricePerSquareMeterFilter?.Active}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.altitude).path)}
				value={values?.Jobs?.AltitudeFilter}
				show={values?.Jobs?.AltitudeFilter?.Active}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.centres).path)}
				value={values?.Jobs?.CentresFilter}
				show={values?.Jobs?.CentresFilter?.Active}
				type={TreeType.JOB}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.snowArea).path)}
				value={values?.Jobs?.SnowAreaFilter?.SnowAreas.map((s) =>
					s === "SnowAreaNotSet" ? t(translationPath(lang.common[s]).path) : s
				)}
				show={values?.Jobs?.SnowAreaFilter?.Active}
				includeNotSetTooltip={t(
					translationPath(lang.common.SnowAreaNotSet).path
				)}
				includeNotSet={values?.SnowAreaFilter?.IncludeNotSet}
				type={TreeType.JOB}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.windArea).path)}
				value={values?.Jobs?.WindAreaFilter?.WindAreas?.map((i) =>
					i === "WindAreaNotSet" ? t(translationPath(lang.common[i]).path) : i
				)}
				show={values?.Jobs?.WindAreaFilter?.Active}
				includeNotSetTooltip={t(
					translationPath(lang.common.WindAreaNotSet).path
				)}
				includeNotSet={values?.Jobs?.WindAreaFilter?.IncludeNotSet}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.snowLoad).path)}
				value={values?.Jobs?.SnowFilter}
				show={values?.Jobs?.SnowFilter?.Active}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.windLoad).path)}
				value={values?.Jobs?.WindFilter}
				show={values?.Jobs?.WindFilter?.Active}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.roofingLoad).path)}
				value={values?.Jobs?.RoofingLoadFilter}
				show={values?.Jobs?.RoofingLoadFilter?.Active}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.ceilingLoad).path)}
				value={values?.Jobs?.CeilingLoadFilter}
				show={values?.Jobs?.CeilingLoadFilter?.Active}
				type={TreeType.JOB}
			/>
			<Row
				title={t(translationPath(lang.common.ceilingName).path)}
				value={values?.Jobs?.CeilingNameFilter?.Name}
				show={values?.Jobs?.CeilingNameFilter?.Active}
				type={TreeType.JOB}
			/>
			<Row
				title={t(translationPath(lang.common.roofingName).path)}
				value={values?.Jobs?.RoofingNameFilter?.Name}
				show={values?.Jobs?.RoofingNameFilter?.Active}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.hipLength).path)}
				value={values?.Jobs?.HipLengthFilter}
				show={values?.Jobs?.HipLengthFilter?.Active}
				type={TreeType.JOB}
			/>
			<SliderRange
				title={t(translationPath(lang.common.roofArea).path)}
				value={values?.Jobs?.CoveredAreaFilter}
				show={values?.Jobs?.CoveredAreaFilter?.Active}
				type={TreeType.JOB}
			/>

			<SliderRange
				title={t(translationPath(lang.common.ridgeLength).path)}
				value={values?.Jobs?.RidgeLengthFilter}
				show={values?.Jobs?.RidgeLengthFilter?.Active}
				type={TreeType.JOB}
			/>
			<DateRange
				title={t(translationPath(lang.common.jobDateOfCreation).path)}
				value={values?.Jobs?.DateOfCreationFilter}
				show={values?.Jobs?.DateOfCreationFilter?.Active}
				type={TreeType.JOB}
			/>
			<DateRange
				title={t(translationPath(lang.common.jobDateOfLastUpdate).path)}
				value={values?.Jobs?.DateOfLastUpdateFilter}
				show={values?.Jobs?.DateOfLastUpdateFilter?.Active}
				type={TreeType.JOB}
			/>
			<Row
				title={t(translationPath(lang.common.truss).path)}
				value={values?.Trusses?.NameFilter?.Name}
				show={!!values?.Trusses?.NameFilter?.Name}
				type={TreeType.TRUSS}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.status).path)}
				value={values?.Trusses?.StatusFilter?.Statuses}
				show={values?.Trusses?.StatusFilter?.Active}
				translate
				type={TreeType.TRUSS}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.trussType).path)}
				value={values?.Trusses?.TypeFilter?.Types}
				show={values?.Trusses?.TypeFilter?.Active}
				translate
				type={TreeType.TRUSS}
			/>
			<MultipleSelect
				title={t(translationPath(lang.common.typeOfTruss).path)}
				value={values?.Trusses?.KindsFilter?.Kinds}
				show={values?.Trusses?.KindsFilter?.Active}
				translate
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.price).path)}
				value={values?.Trusses?.PriceFilter}
				show={values?.Trusses?.PriceFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.windLoad).path)}
				value={values?.Trusses?.WindLoadFilter}
				show={values?.Trusses?.WindLoadFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.snowLoad).path)}
				value={values?.Trusses?.SnowLoadFilter}
				show={values?.Trusses?.SnowLoadFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.ceilingLoad).path)}
				value={values?.Trusses?.CeilingLoadFilter}
				show={values?.Trusses?.CeilingLoadFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.roofingLoad).path)}
				value={values?.Trusses?.RoofingLoadFilter}
				show={values?.Trusses?.RoofingLoadFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.height).path)}
				value={values?.Trusses?.HeightFilter}
				show={values?.Trusses?.HeightFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.length).path)}
				value={values?.Trusses?.LengthFilter}
				show={values?.Trusses?.LengthFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.span).path)}
				value={values?.Trusses?.SpanFilter}
				show={values?.Trusses?.SpanFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.thickness).path)}
				value={values?.Trusses?.ThicknessFilter}
				show={values?.Trusses?.ThicknessFilter?.Active}
				type={TreeType.TRUSS}
			/>

			<SliderRange
				title={t(translationPath(lang.common.centres).path)}
				value={values?.Trusses?.CentresFilter}
				show={values?.Trusses?.CentresFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.trussWeight).path)}
				value={values?.Trusses?.WeightFilter}
				show={values?.Trusses?.WeightFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.transportWeight).path)}
				value={values?.Trusses?.TransportWeightFilter}
				show={values?.Trusses?.TransportWeightFilter?.Active}
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.numberOfSupports).path)}
				value={values?.Trusses?.SupportsQuantityFilter}
				show={values?.Trusses?.SupportsQuantityFilter?.Active}
				round
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.membersCount).path)}
				value={values?.Trusses?.MembersCountFilter}
				show={values?.Trusses?.MembersCountFilter?.Active}
				round
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.platesCount).path)}
				value={values?.Trusses?.PlatesCountFilter}
				show={values?.Trusses?.PlatesCountFilter?.Active}
				round
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.modelCount).path)}
				value={values?.Trusses?.ModelCountFilter}
				show={values?.Trusses?.ModelCountFilter?.Active}
				round
				type={TreeType.TRUSS}
			/>
			<SliderRange
				title={t(translationPath(lang.common.ply).path)}
				value={values?.Trusses?.PliesFilter}
				show={values?.Trusses?.PliesFilter?.Active}
				round
				type={TreeType.TRUSS}
			/>
		</>
	);
};
