name: Continuous Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Deploy staging
        if: github.ref == 'refs/heads/develop'
        run: npm run release:dev
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        run: npm run release:prod
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


