name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Build Electron release
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: gh token
        run: echo ${{ secrets.GH_TOKEN }}
